spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: file:D:\Proyectos\Microservicios\git\ConfigData
          #uri: https://github.com/PabloRomeroGonzalez/ConfigData
          clone-on-start: true
server:
  port: 8001
  